### ISSUE TITLE
REQUEST: PEP 263

### ISSUE THREAD

**Issue by programadorhedonista** [boriel-basic/zxbasic#681]
Ya que actualmente zxbasic necesita python 3, y los ficheros .py tienen codificación utf-8,  se podrían eliminar las líneas
` # -*- coding: utf-8 -*-`
que tenían sentido en python 2.

**Comment by boriel** [comment]
Si, las iré quitando con el tiempo. Gracias! :)

**Comment by boriel** [comment]
This issue with the help of @bartsanchez has been already addressed! :-)
