### ISSUE TITLE
Incorrect W190 and W180

### ISSUE THREAD

**Issue by ulanda** [boriel-basic/zxbasic#822]
Code runs as expected, only issue are the emitted warings.

Minimal repro

```
FUNCTION distance (y1 as uByte, x1 as uByte, y2 as uByte, x2 as ubyte) as uByte
    DIM a,b,c as integer
    a=x1
    a=ABS (a-x2)  ' Height difference
    b=y1
    b=ABS (b-y2)  ' width difference
    c=SQR (a*a + b*b)
    return CAST(uByte,c)
END FUNCTION

print distance(10,10,20,20)

```
Compilation log:
```
Building precompilation documents...
Project path: /Users/uhome/Library/Mobile Documents/com~apple~CloudDocs/boriel/prjs/snake
Building program /Users/uhome/Library/Mobile Documents/com~apple~CloudDocs/boriel/prjs/snake/test.zxbas
Building starts at 1/10/2024 23:53:24
/Users/uhome/Library/Mobile Documents/com~apple~CloudDocs/boriel/prjs/snake/test.zxbas:9: warning: [W190] Function 'distance' should return a value
/Users/uhome/Library/Mobile Documents/com~apple~CloudDocs/boriel/prjs/snake/test.zxbas:9: warning: [W180] Unreachable code
Building postcompilation documents...
Program size: 1603 bytes
Program built successfully (Elapsed time: 00:00:00 seconds)

```

**Comment by boriel** [comment]
Cannot reproduce.
What version of the compiler are you using? What are the compilation options? (command-line flags?)

**Comment by ulanda** [comment]
I'm using zxbasic-1.17.2 and zxbasic-v1.17.3.beta16
Could find the source of the error, it happens when I "enable break" on project configuration.
<img width="407" alt="image" src="https://github.com/user-attachments/assets/353ff5b0-3aa2-4d58-83fe-1a53ea595a95">

**Comment by boriel** [comment]
Confirmed. :-) 
Thanks for reporting!

**Comment by ulanda** [comment]
I just downloaded fina 1.17.3 from the oficialpage and tested same function but  one of the wanigs persists:

> 
```freebasic
FUNCTION distance (y1 as uByte, x1 as uByte, y2 as uByte, x2 as ubyte) as uByte
    DIM a,b,c as integer
    a=x1
    a=ABS (a-x2)  ' Height difference
    b=y1
    b=ABS (b-y2)  ' width difference
    c=SQR (a*a + b*b)
    return CAST(uByte,c)
END FUNCTION

print distance(10,10,20,20)

``` 
Generates this output when compiled for build & debug, no warning is emitted if compiled with just compile, this time no mather of the compile setting the same warning shows up.
```
Building precompilation documents...
Building map files...
Building program map...
/Users/uhome/Library/Mobile Documents/com~apple~CloudDocs/boriel/prjs/snake/test.buildtemp.zxbas:10: warning: [W190] Function 'distance' should return a value
Building variable map...
/Users/uhome/Library/Mobile Documents/com~apple~CloudDocs/boriel/prjs/snake/test.buildtemp.zxbas:10: warning: [W190] Function 'distance' should return a value
Building disassembly...
/Users/uhome/Library/Mobile Documents/com~apple~CloudDocs/boriel/prjs/snake/test.buildtemp.zxbas:10: warning: [W190] Function 'distance' should return a value
Building disassembly map...
Building postcompilation documents...
Program size: 1522 bytes
Program built successfully.

```

**Comment by boriel** [comment]
Is this when using ZXBasicStudio? ZXBS injects some code when using debug mode.

**Comment by ulanda** [comment]
Yes, it happens only when ussing the build & debug option.

**Comment by boriel** [comment]
Try this beta, and let me know if it works for you:
http://www.boriel.com/files/zxb/zxbasic-v1.17.4-beta1.tar.gz
http://www.boriel.com/files/zxb/zxbasic-v1.17.4-beta1.zip
http://www.boriel.com/files/zxb/zxbasic-v1.17.4-beta1-win32.zip
http://www.boriel.com/files/zxb/zxbasic-v1.17.4-beta1-linux64.tar.gz
http://www.boriel.com/files/zxb/zxbasic-v1.17.4-beta1-macos.tar.gz

**Comment by ulanda** [comment]
I can confirm that latest beta removes the W190
