### ISSUE TITLE
Documentation - Bitwise Logic, bAND example is incorrect

### ISSUE THREAD

**Issue by LamptonWorm** [boriel-basic/zxbasic#870]
### Compiler version

v1.17.2

### What happened?

https://zxbasic.readthedocs.io/en/latest/bitwiselogic/
"PRINT BIN 01110111 bAND BIN 00001111 will print 3, which is 0111"
Should read "will print 7"?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by boriel** [comment]
Fixed. Please ensure your browser cache is clean, because readthedocs.org caches *a lot*. :-)
