### ISSUE TITLE
The Bug report form is broken

### ISSUE THREAD

**Issue by bartsanchez** [boriel-basic/zxbasic#923]
If I am not wrong, the bug report template is broken. Even though I fill all the mandatory fields, I can't report a bug.

**Comment by boriel** [comment]
I've just tested and it's working.
You need to check the Agreement checkbox, and fill in all the fields. The only non-mandatory field is the error msg. text field. :-)

**Comment by bartsanchez** [comment]
Oops! Itr's true. The compiler version seemed to me to be already filled but it's not... Sorry.
